version: '3'

services:
  postgresql:
    container_name: postgresql1
    image: postgres:15.2
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
#    volumes:
#      - ./postgres:/data/postgres
#      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "15432:5432"
#  adminer:
#    image: adminer
#    #    restart: always
#    ports:
#      - 8011:8080